---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

```{r}
library(tidyverse)
library(MuMIn)
```

```{r}
bent_water_chem <- read_csv("https://www.epa.gov/sites/production/files/2016-12/nla2012_waterchem_wide.csv")
```

```{r}
benth_met_L2012 <- read_csv("https://www.epa.gov/sites/production/files/2016-11/nla2012_bentmet.csv")


```

```{r}
env_chem_prof_L2012 <- read_csv("https://www.epa.gov/sites/production/files/2016-12/nla2012_wide_profile_08232016.csv")
```

```{r}
env_chem_L2012 <- read.csv("https://www.epa.gov/sites/production/files/2016-12/nla2012_waterchem_wide.csv")
```

```{r}
bent_met_select <- benth_met_L2012 %>% 
  select(SITE_ID, EPT_PTAX) %>% 
  filter(!is.na(EPT_PTAX))

```

```{r}
env_chem_prof_L2012 <- read_csv("https://www.epa.gov/sites/production/files/2016-12/nla2012_wide_profile_08232016.csv") 
```

```{r}
selected_env_chem_prof_L2012 <- env_chem_prof_L2012 %>%
  dplyr::select(UID, SITE_ID, STATE, CONDUCTIVITY, DEPTH, OXYGEN, PH, TEMPERATURE)
View(selected_env_chem_prof_L2012)
```

```{r}
selected_env_chem_prof_L2012new <- selected_env_chem_prof_L2012 %>% 
  mutate(SITE_ID = ifelse((SITE_ID) == "", NA, SITE_ID)) %>% 
  filter(!is.na(SITE_ID)) %>% 
  filter(!is.na(CONDUCTIVITY) & !is.na(DEPTH) & !is.na(OXYGEN) & !is.na(PH) & !is.na(TEMPERATURE)) %>% 
  group_by(SITE_ID, STATE) %>% 
  summarize(Conductivity = mean(CONDUCTIVITY),
            Depth = mean(DEPTH),
            Oxygen = mean(OXYGEN),
            pH = mean(PH), 
            Temperature = mean(TEMPERATURE))
```

```{r}
merged <- right_join(selected_env_chem_prof_L2012new, bent_met_select, by = "SITE_ID")

merged <- merged %>%
  filter(!is.na(STATE))

merged <- merged %>% 
  dplyr::select(Conductivity, Depth, pH, Temperature, Oxygen, EPT_PTAX , SITE_ID)
View(merged)
```

```{r}
merged %>% 
  ggplot(aes(x = Temperature)) +
  geom_histogram()

merged <- merged %>%
  mutate(Temperature = ifelse(Temperature > 50, NA, Temperature)) %>% 
  filter(!is.na(Temperature))

merged %>%
  ggplot(aes(x = Temperature, y = EPT_PTAX)) +
  geom_point()
```

```{r}
lm_ph <- lm(EPT_PTAX ~ pH + Depth , data = merged)
summary(lm_ph)
```


```{r}
model_basic <- lm(EPT_PTAX ~ Depth + Conductivity + Temperature + Oxygen + pH, data = merged)
summary(model_basic)

```

```{r}
model_sat1 <- lm(EPT_PTAX ~ Depth*Temperature + Temperature*Oxygen + Temperature*Conductivity, data = merged)
View(model_sat1)
#model_sat <- lm(EPT_PTAX ~ Conductivity + Depth + Oxygen + pH + Temperature, data = merged)

options(na.action = "na.fail")

Model_dredge <- dredge(model_sat1, beta = F, evaluate = T, rank = AIC)

options(na.action = "na.omit")

summary(Model_dredge)

```

```{r}
top_model <- get.models(Model_dredge, subset = delta <= 2)
top_model
summary(top_model)

```

```{r}
summary(model.avg(top_model))

```

```{r}
model_basic_plot <- lm(EPT_PTAX ~ Conductivity + Depth + Oxygen + Temperature + Conductivity*Temperature + Oxygen*Temperature + Depth*Temperature, data = merged)
plot(model_basic_plot)
summary(model_basic_plot)
```




```{r}
model_selected <- lm(EPT_PTAX ~ Conductivity + Depth + Oxygen + pH + Temperature +  Conductivity:Temperature + Oxygen:Temperature + Depth:Temperature, data = merged)
summary(model_selected)
```

```{r}
Temperature_graph <- merged %>%
  ggplot(aes(x = Temperature, y = EPT_PTAX)) +
  geom_point() +
  geom_smooth(method = "lm") + 
  theme(aspect.ratio = 1, plot.title = element_text(hjust = 0.5)) +
  ggtitle("Temperature vs EPT Taxa %") + 
  xlab("Temperature (°C)") +
  ylab("EPT %") 

Temperature_graph

Oxygen_graph <- merged %>% 
  ggplot(aes(x= Oxygen, y = EPT_PTAX)) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme(aspect.ratio = 1, plot.title = element_text(hjust = 0.5)) +
  ggtitle("Oxygen vs EPT Taxa %") +
  xlab("Dissolved Oxygen (mg/L)") +
  ylab("EPT %")

Oxygen_graph

pH_graph <- merged %>% 
  ggplot(aes(x=pH, y = EPT_PTAX)) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme(aspect.ratio = 1, plot.title = element_text(hjust = 0.5)) +
  ggtitle("pH vs EPT Taxa %") +
  xlab("pH") +
  ylab("EPT %")

pH_graph


Depth_graph <- merged %>% 
  ggplot(aes(x=Depth, y = EPT_PTAX)) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme(aspect.ratio =  1, plot.title = element_text(hjust = 0.5)) +
  ggtitle("Depth vs EPT Taxa %") +
  xlab("Depth (m)") +
  ylab("EPT Taxa %")

Depth_graph


Conductivity_graph <- merged %>% 
  ggplot(aes(x= Conductivity, y = EPT_PTAX)) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme(aspect.ratio = 1, plot.title = element_text(hjust = 0.5)) +
  ggtitle("Conductivity vs EPT Taxa %") +
  xlab("Conductivity (S/m)") +
  ylab("EPT %")

Conductivity_graph
```

#Adjusted R-values
```{r}
pH1<- lm(formula = EPT_PTAX ~ pH, data = merged)
summary(pH1)

Depth1 <- lm(formula = EPT_PTAX ~ Depth, data = merged)
summary(Depth1)

Temperature1 <- lm(formula = EPT_PTAX ~ Temperature, data = merged)
summary(Temperature1)

Conductivity1 <- lm(formula = EPT_PTAX ~ Conductivity, data = merged)
summary(Conductivity1)

Oxygen1 <- lm(formula = EPT_PTAX ~ Oxygen, data = merged)
summary(Oxygen1)

Conduct_Temp <- lm(EPT_PTAX ~ Conductivity + Depth + Oxygen + pH + Temperature + Conductivity*Temperature, data = merged)
summary(Conduct_Temp)

Oxygen_Temp <-lm(EPT_PTAX ~ Conductivity + Depth + Oxygen + pH + Temperature + Oxygen*Temperature, data = merged)
summary(Oxygen_Temp)

Depth_Temp <-lm(EPT_PTAX ~ Conductivity + Depth + Oxygen + pH + Temperature + Depth*Temperature, data = merged)
summary(Depth_Temp)
```

#Significant values
```{r}
model_dredge_fullOutput <- as.data.frame(summary(model.avg(top_model))$coefmat.full)
model_dredge_fullOutput
```
